# [START django_app]
runtime: python
env: flex
entrypoint: gunicorn -b :8080 ProyectoML.wsgi
 
runtime_config:
    python_version: 3
    
manual_scaling: 
    instances: 1
resources:
    cpu: 1
    memory_gb: 4
    disk_size_gb: 15